WebApplication1/Models/Order/Class1.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WebApplication1.Models.Common;

namespace WebApplication1.Models.Order
{
    public class Class1
    {
        public void get交易紀錄()
        {

        }
    }
}

WebApplication1/ViewModels/Order/BuyPointVM.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebApplication1.ViewModels.Order
{
    public class BuyPointVM
    {
        [Key]
        public int fDID { get; set; }

        public int fUID { get; set; }

        [Display(Name = "點數")]
        public int f點數 { get; set; }

        [Display(Name = "建立時間")]
        public System.DateTime f建立時間 { get; set; }
    }


}

WebApplication1/ViewModels/Order/ChefInfoVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication1.ViewModels.Order
{
    public class ChefInfoVM
    {
    }
}

WebApplication1/ViewModels/Order/ClientInfoVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication1.ViewModels.Order
{
    public class ClientInfoVM
    {
    }
}

WebApplication1/ViewModels/Order/v交易紀錄VM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication1.ViewModels.Order
{
    public class v交易紀錄VM
    {
        public int 點數餘額 { get; set; }

        public List<sp_交易紀錄_Result> 交易紀錄 { get; set; }

    }
}

WebApplication1/ViewModels/Order/v儲值點數VM.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebApplication1.ViewModels.Order
{
    public class v儲值點數VM
    {
        
        public int fUID { get; set; }

        [Display(Name = "點數")]
        [Required]
        [Range(1,100000000)]
        public int f點數 { get; set; }

    }


}

WebApplication1/ViewModels/Order/v客戶資訊VM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication1.ViewModels.Order
{
    public class v客戶資訊VM
    {
        public string 客戶姓名 { get; set; }
        public string 客戶照片 { get; set; }
        public string 客戶暱稱 { get; set; }
        public string 電話 { get; set; }
        public string 電子郵件 { get; set; }
    }
}

WebApplication1/ViewModels/Order/v會員中心VM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication1.ViewModels.Order
{
    public class v會員中心VM
    {
        public string 姓名 { get; set; }
        public string 暱稱 { get; set; }
        public string 會員照片 { get; set; }
        public string 電話 { get; set; }
        public string 生日 { get; set; }
        public string 地址 { get; set; }
        public string 電子郵件 { get; set; }
        public int 點數 { get; set; }

        // 私廚
        public int? fCID { get; set; }
        public string 私廚簡介 { get; set; }
        public string 服務地區 { get; set; }
        public string 餐飲風格 { get; set; }
        public string 服務項目 { get; set; }

    }
}

WebApplication1/ViewModels/Order/v登入VM.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebApplication1.ViewModels.Order
{
    public class v登入VM
    {
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "您必須輸入帳號！")]
        public string 帳號 {get; set;}

        [DataType(DataType.Password)]   //表示此欄位為密碼欄位，所以輸入時會產生隱碼
        [Required(ErrorMessage = "您必須輸入密碼！")]
        public string 密碼 { get; set; }
    }
}

WebApplication1/ViewModels/Order/v私廚資訊VM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication1.ViewModels.Order
{

    public class ChefProduct
    {
        public string 項目名稱 { get; set; }
        public int 價格 { get; set; }
        public string 風格 { get; set; }
        public string 服務種類 { get; set; }
        public string 項目照片 { get; set; }
    }



    public class v私廚資訊VM
    {
        public string 私廚姓名 { get; set; }
        public string 私廚照片 { get; set; }
        public int 私廚評級 { get; set; }
        public string 電子郵件 { get; set; }

        public string 服務地區 { get; set; }
        public string 餐飲風格 { get; set; }
        public string 服務種類 { get; set; }
        public string 私廚簡介 { get; set; }

        public List<ChefProduct> 項目清單 { get; set; }

    }
}

WebApplication1/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models.Common;
using WebApplication1.ViewModels.Order;

namespace WebApplication1.Controllers
{
    public class OrderController : Controller
    {
        // GET: Order
        private Database1Entities db = new Database1Entities();




        public ActionResult login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult login(v登入VM 登入VM)
        {
            // 模型驗證
            if (ModelState.IsValid)
            {
                var user = db.t會員.FirstOrDefault(u =>
                    u.f帳號 == 登入VM.帳號 && u.f密碼 == 登入VM.密碼
                );
                // 帳密驗證
                if (user != null)
                {
                    Session.Clear();
                    Session[CDictionary.SK_LOGINED_USER_ID] = user;
                    // 私廚ID
                    //if ((int)user.f權限 == e會員_權限.私廚.GetHashCode())
                    //{
                    //    var chef = db.t私廚.FirstOrDefault(c => c.fUID == user.fUID);
                    //    Session[CDictionary.SK_CHEF_ID] = chef.fCID;
                    //}
                    return RedirectToAction("center");
                }

            }
            return View();
        }

        public ActionResult center()
        {
            if (Session[CDictionary.SK_LOGINED_USER_ID] == null)
            {
                return RedirectToAction("login");
            }

            var user = Session[CDictionary.SK_LOGINED_USER_ID] as t會員;

            var linq = from u in db.t會員
                       join c in db.t私廚
                            on u.fUID equals c.fUID into mixin
                       from x in mixin.DefaultIfEmpty()
                       where u.fUID == user.fUID
                       select new v會員中心VM
                       {
                           姓名 = u.f姓名,
                           暱稱 = u.f暱稱,
                           會員照片 = u.f會員照片,
                           地址 = u.f居住縣市,
                           生日 = u.f生日,
                           電話 = u.f電話,
                           電子郵件 = u.f電子郵件,
                           點數 = u.f點數 ?? 0,
                           fCID = x.fCID,
                           服務地區 = x.f服務地區,
                           私廚簡介 = x.f私廚簡介,
                           服務項目 = x.f服務種類,
                           餐飲風格 = x.f風格
                       };

            return View(linq.FirstOrDefault());
        }

        public ActionResult register()
        {
            if (Session[CDictionary.SK_LOGINED_USER_ID] == null)
            {
                return RedirectToAction("login");
            }
            return View();
        }

        //==========================================================

        public ActionResult buyPoint()
        {
            if (Session[CDictionary.SK_LOGINED_USER_ID] == null)
            {
                return RedirectToAction("login");
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult buyPoint(v儲值點數VM buyPointVM)
        {
            if (ModelState.IsValid)
            {
                if (Session[Models.Common.CDictionary.SK_LOGINED_USER_ID] != null)
                {
                    var user = Session[Models.Common.CDictionary.SK_LOGINED_USER_ID] as t會員;
                    var newPoint = new t儲值點數
                    {
                        fUID = user.fUID,
                        f點數 = buyPointVM.f點數
                    };
                    db.t儲值點數.Add(newPoint);
                    db.SaveChanges();
                    RedirectToAction("buyPointSuccess");
                }
            }
            return RedirectToAction("", "");
        }

        public ActionResult buyPointSuccess()
        {
            return View();
        }

        public ActionResult transaction()
        {
            if (Session[CDictionary.SK_LOGINED_USER_ID] == null)
            {
                return RedirectToAction("login");
            }

            var user = Session[CDictionary.SK_LOGINED_USER_ID] as t會員;
            //var user = db.t會員.FirstOrDefault(u => u.fUID == fUID);

            var linq = db.sp_交易紀錄(user.fUID);

            var 交易紀錄 = new v交易紀錄VM
            {
                點數餘額 = user.f點數 ?? 0,
                交易紀錄 = linq.ToList()
            };

            return View(交易紀錄);
        }

        public ActionResult chefInfo(int fCID)
        {
            // 1.私廚資訊 2.私廚販售項目清單

            // 私廚販售項目清單
            var chefProp = from p in db.t販售項目
                           join s in db.t風格 on p.fSID equals s.fSID
                           join k in db.t服務種類 on p.fKID equals k.fKID
                           where p.fCID == fCID && p.f上架 == true
                           select new ChefProduct
                           {
                               項目名稱 = p.f項目名稱,
                               價格 = p.f價格,
                               風格 = s.f風格,
                               服務種類 = k.f服務種類,
                               項目照片 = p.f項目照片
                           };

            // 私廚資訊
            var linq = from c in db.t私廚
                       join u in db.t會員 on c.fUID equals u.fUID
                       where c.fCID == fCID
                       select new v私廚資訊VM
                       {
                           私廚姓名 = u.f姓名,
                           私廚照片 = u.f會員照片,
                           私廚評級 = c.f私廚評級 == null ? 0 : (int)c.f私廚評級,
                           電子郵件 = u.f電子郵件,
                           服務地區 = c.f服務地區,
                           餐飲風格 = c.f風格,
                           服務種類 = c.f服務種類,
                           私廚簡介 = c.f私廚簡介,
                           項目清單 = chefProp.ToList()
                       };

            var chefinfo = linq.FirstOrDefault();

            return View(chefinfo);
        }

        public ActionResult clientInfo(int fUID)
        {
            var user = db.t會員.FirstOrDefault(u => u.fUID == fUID);
            if (user != null)
            {
                var 客戶資訊 = new v客戶資訊VM
                {
                    客戶姓名 = user.f姓名,
                    客戶暱稱 = user.f暱稱,
                    客戶照片 = user.f會員照片,
                    電子郵件 = user.f電子郵件,
                    電話 = user.f電話
                };
                return View(客戶資訊);
            }
            return View();
        }

        public ActionResult evaluate(int fOID)
        {
            //if (Session[CDictionary.SK_LOGINED_USER_ID] == null)
            //{
            //    return RedirectToAction("login");
            //}
            
            var linq = from o in db.t訂單
                       join p in db.t販售項目 on o.fPID equals p.fPID
                       join k in db.t服務種類 on p.fKID equals k.fKID
                       join c in db.t私廚 on p.fCID equals c.fCID
                       join u in db.t會員 on c.fUID equals u.fUID
                       where o.fOID == fOID
                       select new v評價VM
                       {
                           預定日期 = o.f預定日期,
                           私廚名稱 = u.f姓名,
                           私廚照片 = u.f會員照片,
                           私廚評級 = c.f私廚評級 ?? 0,
                           項目名稱 = p.f項目名稱,
                           項目照片 = p.f項目照片,
                           價格 = p.f價格,
                           服務種類 = k.f服務種類,

                           fOID = fOID
                       };

            return View(linq.FirstOrDefault());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult evaluate(v評價VM vm)
        {
            var order = db.t訂單.FirstOrDefault(o => o.fOID == vm.fOID);

            if (order != null)
            {
                order.f評級 = vm.評級;
                order.f評價內容 = vm.評價內容;
                order.f評價日期 = DateTime.Now.ToString("g");

                order.f狀態 = e訂單狀態.客戶確認_完成評價.GetHashCode();

                db.SaveChanges();

                var chef = (from c in db.t私廚
                            join p in db.t販售項目 on c.fCID equals p.fCID
                            where p.fPID == order.fPID
                            select c).FirstOrDefault();

                //var linq = from c in db.t私廚
                //           join p in db.t販售項目 on c.fCID equals p.fCID
                //           join o in db.t訂單 p.fPID equals o.fPID
                //           where c.fCID == chef.fCID && o.f狀態 == 3
                //           select c; 
                
            }
            return RedirectToAction("transaction");
        }

        public ActionResult salesItem(int fUID, int fPID)
        {

            return View();
        }


        //=========================================================

        public ActionResult List()
        {
            var table = db.t訂單.Select(o => o);
            var list = table.ToList();

            return View(list);
        }

        public ActionResult Create()
        {

            var selectList = db.t訂單.Select(t => t).ToList();

            return View();
        }

        [HttpPost]
        public ActionResult Create(t訂單 o)
        {

            db.t訂單.Add(o);
            db.SaveChanges();

            return RedirectToAction("List");
        }

        public ActionResult Edit(int fOID)
        {
            var order = db.t訂單.FirstOrDefault(o => o.fOID == fOID);

            return View(order);
        }

        [HttpPost]
        public ActionResult Edit(t訂單 modify)
        {
            var order = db.t訂單.FirstOrDefault(o => o.fOID == modify.fOID);

            if (order != null)
            {
                order.fPID = modify.fPID;
                order.fUID = modify.fUID;
                order.f評價日期 = modify.f評價日期;
                order.f數量 = modify.f數量;
                order.f狀態 = modify.f狀態;
                order.f訂購日期 = modify.f訂購日期;

WebApplication1/Controllers/ScheduleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.ViewModels.Schedule;

namespace WebApplication1.Controllers
{
    public class ScheduleController : Controller
    {
        // GET: Schedule

        public ActionResult List(int fCid)
        {

            var table = (from t in (new Database1Entities()).t私廚可預訂時間
                         where t.fCID == fCid
                         select t).ToList();

            var listunable = new List<string>();
            var listenable = new List<string>();

            listunable.AddRange(table.Where(t => t.f狀態 == 2)
                .Select(x => x.f日期.ToString("d") + "-" + x.f時段.ToString()).ToList()
                );

            listenable.AddRange(table.Where(t => t.f狀態 == 1)
                .Select(x => x.f日期.ToString("d") + "-" + x.f時段.ToString()).ToList()
                );


            CScheduleViewModel ScheduleVM = new CScheduleViewModel();
            ScheduleVM.fCid = fCid;
            ScheduleVM.ArrEnable = listenable;
            ScheduleVM.ArrUnable = listunable;

            return View(ScheduleVM);
        }

        [HttpPost]
        public ActionResult List(CScheduleViewModel VM)
        {
            //新增可預訂時間
            string sCreate = VM.ArrGetNewTime;
            if (!string.IsNullOrEmpty(sCreate))
            {
                string[] ArrSplit = sCreate.Split(',');
                Database1Entities dbCreate = new Database1Entities();

                foreach (string s1 in ArrSplit)
                {
                    if (!string.IsNullOrEmpty(s1))
                    {
                        string[] Arr = s1.Split('-');
                        t私廚可預訂時間 t = new t私廚可預訂時間();
                        t.fCID = VM.fCid;
                        t.f日期 = Convert.ToDateTime(Arr[0]);
                        t.f時段 = Convert.ToInt32(Arr[1]);
                        t.f狀態 = 1;
                        dbCreate.t私廚可預訂時間.Add(t);
                    }
                }

                dbCreate.SaveChanges();

            }

            //刪除不可預定時間
            string sDelete = VM.ArrGetDeletedTime;
            
            if (!string.IsNullOrEmpty(sDelete))
            {
                string[] ArrSplitDelete = sDelete.Split(',');
                Database1Entities dbDelete = new Database1Entities();
                foreach (string s in ArrSplitDelete)
                {
                    if (!string.IsNullOrEmpty(s))
                    {
                        string[] Arr = s.Split('-');
                        DateTime time = Convert.ToDateTime(Arr[0]);
                        int status = Convert.ToInt32(Arr[1]);
                        var deleteTime = dbDelete.t私廚可預訂時間.FirstOrDefault(t => t.f日期 == time && t.f時段 == status);
                        if (deleteTime != null)
                        {
                            dbDelete.t私廚可預訂時間.Remove(deleteTime);

                        }
                    }
                }
                dbDelete.SaveChanges();

            }
            return RedirectToAction("List", new { fCid = VM.fCid });
        }
    }
}

WebApplication1/Views/Order/List.cshtml
@model IEnumerable<WebApplication1.t訂單>

@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>List</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        
        <th>
            @Html.DisplayNameFor(model => model.fUID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fPID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.f訂購日期)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.f預定日期)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.f完成日期)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.f數量)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.f總價)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.f狀態)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.f評級)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.f評價內容)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
       
        <td>
            @Html.DisplayFor(modelItem => item.fUID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.fPID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.f訂購日期)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.f預定日期)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.f完成日期)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.f數量)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.f總價)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.f狀態)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.f評級)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.f評價內容)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { fOID=item.fOID}) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { fOID = item.fOID })
        </td>
    </tr>
}

</table>

WebApplication1/Views/Order/center.cshtml
@model WebApplication1.ViewModels.Order.v會員中心VM
@{
    ViewBag.Title = "會員中心";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

@section Breadcumb {
    @{ Html.RenderPartial("~/Views/Shared/_Breadcumb一般.cshtml"); }
}


<!-- ##### clientinfo Start ##### -->
<div class="contact-area section-padding-0-80">
    <div class="container p-0">
        <table style="width: 100%;" class="mt-5 mb-3">
            <tr>
                <td style="width: 90%;">
                    <span class="m-1 noclick">基本資料</span>
                    <span class="ml-4 mr-4"><i class="fa fa-dot-circle-o" aria-hidden="true"></i>　點數餘額：@Model.點數 點</span>
                    <a href="@Url.Action("buyPoint","Order")">
                        <span style="color: #ffa943;">
                            <i class="fa fa-plus"
                               aria-hidden="true"></i>　儲值點數
                        </span>
                    </a>
                </td>
                <td class="text-right" style="width: 10%;">
                    <a href="@Url.Action("memberInfoEdit","Order")" style="right: 0;">
                        <h5><i class="fa fa-pencil-square-o" aria-hidden="true" style="color: #8b8b8b;"></i></h5>
                    </a>
                </td>
            </tr>
        </table>
    </div>
    <div class="container single-best-receipe-area">
        <div class="row">
            <div class="col-12">
                <div class="row">
                    <div class="col-lg-4 p-0 ">
                        <div class="picautosize">
                            <div class="img-style3" style="background-image: url(@Model.會員照片);"></div>
                        </div>
                    </div>
                    <div class="col-lg-8 card-bg3">
                        <div class="mb-3"><span style="font-size: 16px;" class="mr-3"><b>@Model.姓名</b></span></div>
                        <div class="mb-3"><b class="mr-5">暱　　稱</b><span>@Model.暱稱</span></div>
                        <div class="mb-3"><b class="mr-5">電　　話</b><span>@Model.電話</span></div>
                        <div class="mb-3"><b class="mr-5">電子郵件</b><span>@Model.電子郵件</span></div>
                        <div class="mb-3"><b class="mr-5">生　　日</b><span>@Model.生日</span></div>
                        <div class=""><b class="mr-5">地　　址</b><span>@Model.地址</span></div>
                    </div>


                </div>
            </div>
        </div>
    </div>
    @{
        if (Model.fCID != null)
        {
            <div class="container p-0">
                <table style="width: 100%;" class="mt-5 mb-3">
                    <tr>
                        <td style="width: 50%;"><span class="m-1 noclick">私廚簡介</span>
                        <td class="text-right" style="width: 50%;">
                            <a href="@Url.Action("chefEdit","Order")" style="right: 0;">
                                <h5><i class="fa fa-pencil-square-o" aria-hidden="true" style="color: #8b8b8b;"></i></h5>
                            </a>
                        </td>
                    </tr>
                </table>
                <div class="row">
                    <div class="col-12 card-bg3">
                        <table style="line-height: 36px;">
                            <tr>
                                <td style="width: 130px;" class="pl-4"><b>服務地區</b></td>
                                <td>@Model.服務地區</td>
                            </tr>
                            <tr>
                                <td class="pl-4"><b>餐飲風格</b></td>
                                <td>@Model.餐飲風格</td>
                            </tr>
                            <tr>
                                <td class="pl-4"><b>服務項目</b></td>
                                <td>@Model.服務項目</td>
                            </tr>
                            <tr>
                                <td style="vertical-align:text-top;" class="pl-4"><b>私廚簡介</b></td>
                                <td class="pr-4">
                                    @Model.私廚簡介
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
            <div class="container p-0">
                <table style="width: 100%;" class="mt-5 mb-3">
                    <tr>
                        <td><span class="m-1 noclick">服務設定</span>
                    </tr>
                </table>


                <div class="row delicious-buttons-area mb-80  text-center">
                    <div class="col-12">
                        <div class="row">
                            <div class="col-lg-6">
                                <a href="@Url.Action("List","Schedule")" class="btn delicious-btn btn-4 m-1" style="width: 100%;">可預訂時間</a>
                            </div>
                            <div class="col-lg-6">
                                <a href="@Url.Action("salesItemList","Schedule")" class="btn delicious-btn btn-4 m-1" style="width: 100%;">販售項目</a>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        }
        else
        {
            <div class="container mt-5 mb-5 text-center">
                <div class="delicious-buttons-area mb-80">
                    <a href="@Url.Action("chefCreate","Order")" class="btn delicious-btn btn-4 m-1">成為私廚</a>
                </div>
            </div>
        }
    }

</div>
<!-- ##### clientinfo End ##### -->

WebApplication1/Views/Order/transaction.cshtml
@model WebApplication1.ViewModels.Order.v交易紀錄VM
@{
    ViewBag.Title = "交易紀錄";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}


<!-- ##### transaction Start ##### -->
<div class="contact-area section-padding-0-80">
    <div class="container p-0 mt-5 mb-5">
        <span class="ml-4 mr-4"><i class="fa fa-dot-circle-o" aria-hidden="true"></i>　@Model.點數餘額</span>
        <a href="@Url.Action("buyPoint","Order")">
            <span style="color: #ffa943;">
                <i class="fa fa-plus"
                   aria-hidden="true"></i>　儲值點數
            </span>
        </a>
    </div>
    <div class="container">
        @{
            foreach (var item in Model.交易紀錄)
            {
                if (item.行為 == "儲值")
                {
                    <table class="tbrecord">
                        <tr>
                            <td><span class="span_left">@item.日期</span></td>
                            <td><span></span></td>
                            <td rowspan="2" class="addpoint"><i class="fa fa-plus" style="margin-right: 10px;"></i>@item.點數 點</td>
                        </tr>
                        <tr>
                            <td class="tbrecord_tb"><span>儲值點數</span></td>
                            <td></td>
                        </tr>
                    </table>
                }
                else if (item.行為 == "消費")
                {
                    <table class="tbrecord">
                        <tr>
                            <td><span class="span_left">@item.日期</span></td>
                            <td rowspan="2" class="statussytle">
                                @{

                                    if (item.狀態 == WebApplication1.Models.Common.e訂單狀態.客戶預訂.GetHashCode().ToString())
                                    {
                                        @:等待服務
                                    }
                                    else if (item.狀態 == WebApplication1.Models.Common.e訂單狀態.私廚確認_開放客戶評價.GetHashCode().ToString())
                                    {
                                        @* 客戶確認_客戶評價 *@
                                        <a href="@Url.Action("evaluate", "Order", new { fOID = item.訂單ID })"><span class="redstatus">完成確認前往評價<i class="fa fa-question-circle-o" aria-hidden="true" title="5天後未完成評價，將自動評為5顆星並撥款給私廚。"></i></span></a>
                                    }
                                    else if (item.狀態 == WebApplication1.Models.Common.e訂單狀態.客戶確認_完成評價.GetHashCode().ToString())
                                    {
                                        <span class="bluestatus">已完成評價 </span>
                                    }
                                }
                                <br>@item.預定日期
                            </td>
                            <td rowspan="2" class="lesspoint"><i class="fa fa-minus" style="margin-right: 10px;"></i>@item.點數 點</td>
                        </tr>
                        <tr>
                            
                            <td class="tbrecord_tb"><span>消費 - <a href="salesitem.html">@item.項目名稱</a> - <a href="@Url.Action("chefInfo", "Order", new { fUID = item.聯絡人ID.ToString() })">@item.聯絡人</a></span></td>
                        </tr>
                    </table>
                }
                else if (item.行為 == "收益")
                {

                    <table class="tbrecord">
                        <tr>
                            <td><span class="span_left">@item.日期</span></td>
                            <td rowspan="2" class="statussytle">
                                @{
                                    if (item.狀態 == WebApplication1.Models.Common.e訂單狀態.客戶預訂.GetHashCode().ToString())
                                    {
                                        @:等待服務
                                    }
                                    else if (item.狀態 == WebApplication1.Models.Common.e訂單狀態.私廚確認_開放客戶評價.GetHashCode().ToString())
                                    {
                                        <span class="waitstatus">待服務 <i class="fa fa-long-arrow-right" aria-hidden="true"></i> </span>
                                        @* 私廚完成服務 未有連結 *@
                                        <a href="#"><span class="redstatus">完成服務 <i class="fa fa-question-circle-o" aria-hidden="true" title="若已完成服務項目，請點擊「完成服務」，變更客戶的交易狀態後，客戶才能於平台給予您評價。若未點擊「完成服務」，將視為尚未服務。"></i></span></a>
                                    }
                                    else if (item.狀態 == WebApplication1.Models.Common.e訂單狀態.客戶確認_完成評價.GetHashCode().ToString())
                                    {
                                        <span class="bluestatus">完成並獲得評價</span>
                                    }
                                }
                                <br>@item.預定日期
                            </td>
                            <td rowspan="2" class="waitpoint"><i class="fa fa-plus" style="margin-right: 10px;"></i>@item.點數 點</td>
                        </tr>
                        <tr>
                            <td class="tbrecord_tb"><span>收益 - <a href="salesitem.html">@item.項目名稱</a> - <a href="@Url.Action("chefInfo", "Order", new { fCID = item.聯絡人ID.ToString() })">@item.聯絡人</a></span></td>
                        </tr>
                    </table>
                }

            }
        }
    </div>
</div>
<!-- ##### transaction End ##### -->