WebApplication1/Controllers/FontendController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    
    public class FontendController : Controller
    {
        // GET: Fontend

        // 登入
        public ActionResult login()
        {
            return View();
        }

        #region 會員中心{ [註冊 註冊成功] [編輯基本資料 編輯私廚簡介] [會員中心(一般) 會員中心(私廚)] [我的最愛] }

        // 註冊
        public ActionResult register()
        {
            return View();
        }

        // 註冊成功
        public ActionResult registersuccess()
        {
            return View();
        }

        // 編輯基本資料
        public ActionResult memberinfo()
        {
            return View();
        }

        // 編輯私廚簡介
        public ActionResult chefedit()
        {
            return View();
        }

        // 會員中心(私廚)
        public ActionResult chefcenter()
        {
            return View();
        }

        // 會員中心(一般)
        public ActionResult membercenter()
        {
            return View();
        }

        // 我的最愛
        public ActionResult favorite()
        {
            return View();
        }

        #endregion

        #region 交易紀錄{ [儲值點數 儲值成功] [交易紀錄] [私廚資訊] [客戶資訊] [填寫評價] }

        // 儲值點數
        public ActionResult buypoint() // OK
        {
            return View();
        }

        // 儲值成功
        public ActionResult buypointsuccess() // OK
        {
            return View();
        }

        // 品項訂購
        public ActionResult salesitem()
        {
            return View();
        }

        // 交易紀錄
        public ActionResult transaction() // OK
        {
            return View();
        }

        // 私廚資訊
        public ActionResult chefinfo() // OK
        {
            return View();
        }

        // 客戶資訊
        public ActionResult clientinfo() // OK
        {
            return View();
        }

        // 填寫評價
        public ActionResult evaluate()
        {
            return View();
        }

        #endregion

        #region 私廚{ [私廚販售項目清單] [新增販售項目] [新增菜色] [設定可預訂時間] }

        // 私廚販售項目清單
        public ActionResult salesitemlist()
        {
            return View();
        }

        // 新增販售項目
        public ActionResult productinfo()
        {
            return View();
        }

        // 新增 - 販售項目 - 菜色
        public ActionResult dishesinfo()
        {
            return View();
        }

        // 設定可預訂時間
        public ActionResult calendar()
        {
            return View();
        }

        #endregion

        // 首頁 
        public ActionResult index()
        {
            return View();
        }

        // 搜尋結果 
        public ActionResult searchlist()
        {
            return View();
        }

    }
}

WebApplication1/Views/Fontend/buyPointSuccess.cshtml
@{
    ViewBag.Title = "儲值成功";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

@section Breadcumb {
    @{ Html.RenderPartial("~/Views/Shared/_Breadcumb一般.cshtml"); }
}

<div class="contact-area section-padding-0-80">
    <div class="container">
        <div class="row">
            <div class="col-12 text-center mt-5">
                <span>將於<span id="seconds"></span>秒後為您跳轉至交易紀錄頁面。</span><br><br>
                <span>
                    或者自行點擊<a href="@Url.Action("buypoint", "Fontend")" class="single-contact-information">
                        <h6>交易紀錄</h6><!--交易紀錄好要改連結-->
                    </a>
                </span>
            </div>
        </div>
    </div>
</div>

@section scripts {

    <script>
        {
            let t = 6;
            function reciprocal() {
                t -= 1;
                document.getElementById('seconds').innerHTML = t;
                if (t == 0) {
                    location.href = "@Url.Action("buypoint", "Fontend")"; //之後交易紀錄好要改連結
                }
                // 不能在 IIFE 裡,會找不到 func
                setTimeout("reciprocal()", 1000);
            }
            window.onload = reciprocal;
        }
    </script>
}

WebApplication1/Views/Fontend/clientinfo.cshtml
@{
    ViewBag.Title = "客戶資訊";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

@section styles {
    <style>
        .clientinfo-bg {
            width: 250px;
            left: 0;
            background-color: #8f8f8f;
            padding: 14px;
            padding-bottom: 13px;
        }
    </style>
}

@section Breadcumb {
    @{ Html.RenderPartial("~/Views/Shared/_Breadcumb一般.cshtml"); }
}

<!-- ##### clientinfo Start ##### -->
<div class="contact-area section-padding-0-80">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="row">
                    <div class="card-middle">
                        <div class="col-12 d-flex flex-wrap mt-5 card-style">
                            <img class="img-style2" src="/Content/img/bg-img/r1.jpg" alt="">
                            <div class="card-bg2">
                                <h6>真實姓名</h6>
                                <div class="mb-2 mt-3"><b class="mr-5">暱　　稱</b><span>羊羊</span></div>
                                <div class="mb-2"><b class="mr-5">電　　話</b><span>0911-111-111</span></div>
                                <div class="mb-2"><b class="mr-5">電子郵件</b><span>test@gmail.com</span></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- ##### clientinfo End ##### -->

WebApplication1/Views/Fontend/register.cshtml
@{
    ViewBag.Title = "註冊";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

@section Breadcumb {
    @{ Html.RenderPartial("~/Views/Shared/_Breadcumb一般.cshtml"); }
}

<!-- ##### Register Start ##### -->
<div class="contact-area section-padding-0-80">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="contact-form-area">
                    <form action="@Url.Action("registersuccess", "Fontend")" method="post">
                        <div class="row">
                            <div class="col-12 mt-5">
                                <input type="text" class="form-control" id="account" placeholder="帳號" required>
                            </div>
                            <div class="col-12 mt-2">
                                <input type="password" class="form-control" id="password1" placeholder="密碼"
                                       required>
                            </div>
                            <div class="col-12 mt-2">
                                <input type="password" class="form-control" id="password2" placeholder="確認密碼"
                                       onchange="checkpw()" required>
                            </div>
                            <div id="msg" class="msg-style2"></div>
                            <div class="col-12 mt-2">
                                <input type="email" class="form-control" id="email" placeholder="電子郵件" required>
                            </div>

                            <div class="col-12 text-center">
                                <button class="btn delicious-btn mt-30" type="submit" id="btn">註冊</button>
                            </div>
                            <div class="col-12 text-right mt-4">
                                <span>
                                    已經有帳號了？點擊 <a href="@Url.Action("registersuccess", "Fontend")" class="single-contact-information">
                                        <h6>登入</h6>
                                    </a>
                                </span>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- ##### Register End ##### -->

@section scripts {
    <script>
        {
            function checkpw() {
                var pw1 = $('input[id=password1]').val();
                var pw2 = $('input[id=password2]').val();
                if (pw1 != pw2) {
                    $('#msg').html('密碼與確認密碼不一致。');
                    $("#btn").attr("disabled", true);
                }
                else {
                    $('#msg').html('');
                    $("#btn").attr("disabled", false);
                }

            }
        }
    </script>
}

WebApplication1/Views/Fontend/registersuccess.cshtml
@{
    ViewBag.Title = "註冊成功";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

@section Breadcumb {
    @{ Html.RenderPartial("~/Views/Shared/_Breadcumb一般.cshtml"); }
}

<!-- ##### Register Start ##### -->
<div class="contact-area section-padding-0-80">
    <div class="container">
        <div class="row">
            <div class="col-12 text-center mt-5">
                <span>將於<span id="seconds"></span>秒後為您跳轉至登入頁面。</span><br><br>
                <span>
                    或者自行點擊<a href="@Url.Action("register", "Fontend")" class="single-contact-information">
                        <h6>登入</h6>
                    </a>
                </span>
            </div>
        </div>
    </div>
</div>
<!-- ##### Register End ##### -->

@section scripts {

    <script>
        {
            let t = 6;
            function reciprocal() {
                t -= 1;
                document.getElementById('seconds').innerHTML = t;
                if (t == 0) {
                    location.href = "@Url.Action("register", "Fontend")"; //之後交易紀錄好要改連結
                }
                setTimeout("reciprocal()", 1000);
            }
            window.onload = reciprocal;
        }
    </script>
}

WebApplication1/Views/Fontend/salesitemlist.cshtml
@{
    ViewBag.Title = "販售項目";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

@section Breadcumb {
    @{ Html.RenderPartial("~/Views/Shared/_Breadcumb一般.cshtml"); }
}

<div class="container mt-5 mb-5">

    <a href="productinfo.html">
        <span class="newitem">
            <i class="fa fa-plus" aria-hidden="true"></i>
            新增販售項目
        </span>
    </a>
</div>
<div class="container">

    <div class="accordions mb-80" id="accordion" role="tablist" aria-multiselectable="true">

        <!-- Single Accordian Area -->
        <div class="panel single-accordion">
            <h6>
                <a role="button" class="" aria-expanded="true" aria-controls="collapseOne" data-toggle="collapse"
                   data-parent="#accordion" href="#collapseOne">
                    1.套餐/課程名稱-風格-服務項目
                    <span class="accor-open"><i class="fa fa-plus" aria-hidden="true"></i></span>
                    <span class="accor-close"><i class="fa fa-minus" aria-hidden="true"></i></span>
                </a>
            </h6>
            <div id="collapseOne" class="accordion-content collapse show">
                <table>
                    <tr>
                        <td rowspan="3" style="width:20%; padding: 0; min-width: 200px;" class="img-style5"
                            background="/Content/img/bg-img/insta1.jpg"></td>
                        <td colspan="2" class="product_td">
                            <h6>主要內容</h6>
                        </td>
                        <td rowspan="3" class="text-left pl-4 table-border" style="width: 10%;">
                            <div class="custom-control custom-checkbox ">
                                <input type="checkbox" class="custom-control-input" id="customCheck1">
                                <label class="custom-control-label" for="customCheck1"><a>上架</a></label>
                            </div>
                            <a href="@Url.Action("productinfo","Fontend")" class="pd1px"><i class="fa fa-plus"></i><span class="pl-2"> 菜色</span></a><br>
                            <a href="@Url.Action("productinfo","Fontend")" class="pd1px"><i class="fa fa-edit"></i><span class="pl-2">編輯</span></a><br>
                            <a href="#" class="pd1px"><i class="fa fa-trash"></i><span class="pl-2"> 刪除</span></a>
                        </td>
                    </tr>
                    <td class="product_td" style="width: 100px;min-width: 100px;"><b>價格:</b></td>
                    <td class="product_td">NT$500/人</td>
                    <tr>
                        <td class="product_td table-bottom" style="width:10%;"><b>詳細內容:</b></td>
                        <td class="product_td table-bottom">詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容</td>
                    </tr>

                    <tr>
                        <td rowspan="3" style="padding: 0;" class="img-style5" background="/Content/img/bg-img/insta2.jpg"></td>
                        <td colspan="2" class="product_td">
                            <h6>菜色1</h6>
                        </td>
                        <td rowspan="3" class="text-left pl-4 table-border">

                            <a href="@Url.Action("dishesinfo","Fontend")"><i class="fa fa-edit"></i><span class="pl-2">編輯</span></a><br>
                            <a href="@Url.Action("dishesinfo","Fontend")"><i class="fa fa-trash"></i><span class="pl-2"> 刪除</span></a>
                        </td>
                    </tr>
                    <td class="product_td"><b>菜名:</b></td>
                    <td class="product_td">宮保雞丁</td>
                    <tr>
                        <td class="product_td table-bottom"><b>菜色內容:</b></td>
                        <td class="product_td table-bottom">詳細內容詳細內容詳細內容詳細內詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容容詳細內容詳細內容</td>
                    </tr>

                    <tr>
                        <td rowspan="3" style="padding: 0;" class="img-style5" background="/Content/img/bg-img/insta3.jpg"></td>
                        <td colspan="2" class="product_td">
                            <h6>菜色2</h6>
                        </td>
                        <td rowspan="3" class="text-left pl-4 table-border">

                            <a href="@Url.Action("dishesinfo","Fontend")"><i class="fa fa-edit"></i><span class="pl-2">編輯</span></a><br>
                            <a href="@Url.Action("dishesinfo","Fontend")"><i class="fa fa-trash"></i><span class="pl-2"> 刪除</span></a>
                        </td>
                    </tr>
                    <td class="product_td"><b>菜名:</b></td>
                    <td class="product_td">宮保雞丁</td>
                    <tr>
                        <td class="product_td table-bottom"><b>菜色內容</b>:</td>
                        <td class="product_td table-bottom">詳細內容詳細內容詳細內容詳細內詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容容詳細內容詳細內容</td>
                    </tr>
                </table>
            </div>
        </div>

        <!-- Single Accordian Area -->
        <div class="panel single-accordion">
            <h6>
                <a role="button" class="collapsed" aria-expanded="true" aria-controls="collapseTwo"
                   data-parent="#accordion" data-toggle="collapse" href="#collapseTwo">
                    2.套餐/課程名稱-風格-服務項目
                    <span class="accor-open"><i class="fa fa-plus" aria-hidden="true"></i></span>
                    <span class="accor-close"><i class="fa fa-minus" aria-hidden="true"></i></span>
                </a>
            </h6>
            <div id="collapseTwo" class="accordion-content collapse">
                <table class="product_detail ">
                    <tr>
                        <td rowspan="3" style="width:20%; padding: 0; min-width: 200px;" class="img-style5"
                            background="/Content/img/bg-img/insta4.jpg"></td>
                        <td colspan="2" class="product_td">
                            <h6>主要內容</h6>
                        </td>
                        <td rowspan="3" class="text-left pl-4 table-border" style="width: 10%;">
                            <div class="ingredients">
                                <div class="custom-control custom-checkbox ">
                                    <input type="checkbox" class="custom-control-input" id="customCheck2">
                                    <label class="custom-control-label" for="customCheck2"><a>上架</a></label>
                                </div>
                            </div>
                            <a href="#" class="pd1px"><i class="fa fa-plus"></i><span class="pl-2"> 菜色</span></a><br>
                            <a href="@Url.Action("productinfo","Fontend")" class="pd1px"><i class="fa fa-edit"></i><span class="pl-2">編輯</span></a><br>
                            <a href="@Url.Action("productinfo","Fontend")" class="pd1px"><i class="fa fa-trash"></i><span class="pl-2"> 刪除</span></a>
                        </td>
                    </tr>
                    <td class="product_td" style="width: 100px;min-width: 100px;"><b>價格:</b></td>
                    <td class="product_td">NT$500/人</td>
                    <tr>
                        <td class="product_td table-bottom" style="width:10%;"><b>詳細內容:</b></td>
                        <td class="product_td table-bottom">詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容</td>
                    </tr>

                    <tr>
                        <td rowspan="3" style="padding: 0;" class="img-style5" background="/Content/img/bg-img/insta5.jpg"></td>
                        <td colspan="2" class="product_td">
                            <h6>菜色1</h6>
                        </td>
                        <td rowspan="3" class="text-left pl-4 table-border">

                            <a href="@Url.Action("productinfo","Fontend")"><i class="fa fa-edit"></i><span class="pl-2">編輯</span></a><br>
                            <a href="#"><i class="fa fa-trash"></i><span class="pl-2"> 刪除</span></a>
                        </td>
                    </tr>
                    <td class="product_td"><b>菜名:</b></td>
                    <td class="product_td">宮保雞丁</td>
                    <tr>
                        <td class="product_td table-bottom"><b>菜色內容:</b></td>
                        <td class="product_td table-bottom">詳細內容詳細內容詳細內容詳細內詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容容詳細內容詳細內容</td>
                    </tr>

                    <tr>
                        <td rowspan="3" style="padding: 0;" class="img-style5" background="/Content/img/bg-img/insta6.jpg"></td>
                        <td colspan="2" class="product_td">
                            <h6>菜色2</h6>
                        </td>
                        <td rowspan="3" class="text-left pl-4 table-border">

                            <a href="#"><i class="fa fa-edit"></i><span class="pl-2">編輯</span></a><br>
                            <a href="#"><i class="fa fa-trash"></i><span class="pl-2"> 刪除</span></a>
                        </td>
                    </tr>
                    <td class="product_td"><b>菜名:</b></td>
                    <td class="product_td">宮保雞丁</td>
                    <tr>
                        <td class="product_td table-bottom"><b>菜色內容</b>:</td>
                        <td class="product_td table-bottom">詳細內容詳細內容詳細內容詳細內詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容容詳細內容詳細內容</td>
                    </tr>
                </table>
            </div>
        </div>

        <!-- Single Accordian Area -->
        <div class="panel single-accordion">
            <h6>
                <a role="button" aria-expanded="true" aria-controls="collapseThree" class="collapsed"
                   data-parent="#accordion" data-toggle="collapse" href="#collapseThree">
                    3.套餐/課程名稱-風格-服務項目
                    <span class="accor-open"><i class="fa fa-plus" aria-hidden="true"></i></span>
                    <span class="accor-close"><i class="fa fa-minus" aria-hidden="true"></i></span>
                </a>
            </h6>
            <div id="collapseThree" class="accordion-content collapse">
                <table class="product_detail ">
                    <tr>
                        <td rowspan="3" style="width:20%; padding: 0; min-width: 200px;" class="img-style5"
                            background="/Content/img/james-img/1.jpg"></td>
                        <td colspan="2" class="product_td">
                            <h6>主要內容</h6>
                        </td>
                        <td rowspan="3" class="text-left pl-4 table-border" style="width: 10%;">
                            <div class="custom-control custom-checkbox ">
                                <input type="checkbox" class="custom-control-input" id="customCheck3">
                                <label class="custom-control-label" for="customCheck3"><a>上架</a></label>
                            </div>
                            <a href="#" class="pd1px"><i class="fa fa-plus"></i><span class="pl-2"> 菜色</span></a><br>
                            <a href="#" class="pd1px"><i class="fa fa-edit"></i><span class="pl-2">編輯</span></a><br>
                            <a href="#" class="pd1px"><i class="fa fa-trash"></i><span class="pl-2"> 刪除</span></a>
                        </td>
                    </tr>
                    <td class="product_td" style="width: 100px;min-width: 100px;"><b>價格:</b></td>
                    <td class="product_td">NT$500/人</td>
                    <tr>
                        <td class="product_td table-bottom" style="width:10%;"><b>詳細內容:</b></td>
                        <td class="product_td table-bottom">詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容</td>
                    </tr>

                    <tr>
                        <td rowspan="3" style="padding: 0;" class="img-style5" background="/Content/img/james-img/1.jpg"></td>
                        <td colspan="2" class="product_td">
                            <h6>菜色1</h6>
                        </td>
                        <td rowspan="3" class="text-left pl-4 table-border">

                            <a href="#"><i class="fa fa-edit"></i><span class="pl-2">編輯</span></a><br>
                            <a href="#"><i class="fa fa-trash"></i><span class="pl-2"> 刪除</span></a>
                        </td>
                    </tr>
                    <td class="product_td"><b>菜名:</b></td>
                    <td class="product_td">宮保雞丁</td>
                    <tr>
                        <td class="product_td table-bottom"><b>菜色內容:</b></td>
                        <td class="product_td table-bottom">詳細內容詳細內容詳細內容詳細內詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容容詳細內容詳細內容</td>
                    </tr>

                    <tr>
                        <td rowspan="3" style="padding: 0;" class="img-style5" background="/Content/img/james-img/1.jpg"></td>
                        <td colspan="2" class="product_td">
                            <h6>菜色2</h6>
                        </td>
                        <td rowspan="3" class="text-left pl-4 table-border">

                            <a href="#"><i class="fa fa-edit"></i><span class="pl-2">編輯</span></a><br>
                            <a href="#"><i class="fa fa-trash"></i><span class="pl-2"> 刪除</span></a>
                        </td>
                    </tr>
                    <td class="product_td"><b>菜名:</b></td>
                    <td class="product_td">宮保雞丁</td>
                    <tr>
                        <td class="product_td table-bottom"><b>菜色內容</b>:</td>
                        <td class="product_td table-bottom">詳細內容詳細內容詳細內容詳細內詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容容詳細內容詳細內容</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>

WebApplication1/Views/Fontend/transaction.cshtml
@{
    ViewBag.Title = "交易紀錄";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

@section Breadcumb {
    @{ Html.RenderPartial("~/Views/Shared/_Breadcumb一般.cshtml"); }
}

<!-- ##### transaction Start ##### -->
<div class="contact-area section-padding-0-80">
    <div class="container p-0 mt-5 mb-5">
        <span class="ml-4 mr-4"><i class="fa fa-dot-circle-o" aria-hidden="true"></i>　點數餘額：0點</span>
        <a href="buypoint.html">
            <span style="color: #ffa943;">
                <i class="fa fa-plus"
                   aria-hidden="true"></i>　儲值點數
            </span>
        </a>
    </div>
    <div class="container">
        <table class="tbrecord">
            <tr>
                <td><span class="span_left">2020-10-10 14:00</span></td>
                <td><span></span></td>
                <td rowspan="2" class="addpoint"><i class="fa fa-plus" style="margin-right: 10px;"></i>500點</td>
            </tr>
            <tr>
                <td class="tbrecord_tb"><span>儲值點數</span></td>
                <td></td>
            </tr>
        </table>
        <table class="tbrecord">
            <tr>
                <td><span class="span_left">2020-10-10 14:00</span></td>
                <td rowspan="2" class="statussytle">等待服務<br>2020-11-17 午餐</td>
                <td rowspan="2" class="lesspoint"><i class="fa fa-minus" style="margin-right: 10px;"></i>500點</td>
            </tr>
            <tr>
                <td class="tbrecord_tb"><span>消費 - <a href="@Url.Action("salesitem","Fontend")">套餐/課程名稱</a> - <a href="@Url.Action("chefinfo","Fontend")">私廚名稱</a></span></td>
            </tr>
        </table>
        <table class="tbrecord">
            <tr>
                <td><span class="span_left">2020-10-10 14:00</span></td>
                <td rowspan="2" class="statussytle"><a href="@Url.Action("evaluate","Fontend")"><span class="redstatus">完成確認前往評價 <i class="fa fa-question-circle-o" aria-hidden="true" title="5天後未完成評價，將自動評為5顆星並撥款給私廚。"></i></span></a><br>2020-11-17 午餐</td>
                <td rowspan="2" class="lesspoint"><i class="fa fa-minus" style="margin-right: 10px;"></i>500點</td>
            </tr>
            <tr>
                <td class="tbrecord_tb"><span>消費 - <a href="@Url.Action("salesitem","Fontend")">套餐/課程名稱</a> - <a href="@Url.Action("chefinfo","Fontend")">私廚名稱</a></span></td>
            </tr>
        </table>

        <table class="tbrecord">
            <tr>
                <td><span class="span_left">2020-10-10 14:00</span></td>
                <td rowspan="2" class="statussytle"><span class="bluestatus">已完成評價 </span><br>2020-11-17 午餐</td>
                <td rowspan="2" class="lesspoint"><i class="fa fa-minus" style="margin-right: 10px;"></i>500點</td>
            </tr>
            <tr>
                <td class="tbrecord_tb"><span>消費 - <a href="@Url.Action("salesitem","Fontend")">套餐/課程名稱</a> - <a href="@Url.Action("chefinfo","Fontend")">私廚名稱</a></span></td>
            </tr>
        </table>

        <table class="tbrecord">
            <tr>
                <td><span class="span_left">2020-10-10 14:00</span></td>
                <td rowspan="2" class="statussytle"><span class="waitstatus">待服務 <i class="fa fa-long-arrow-right" aria-hidden="true"></i> </span> <a href="#"><span class="redstatus">完成服務 <i class="fa fa-question-circle-o" aria-hidden="true" title="若已完成服務項目，請點擊「完成服務」，變更客戶的交易狀態後，客戶才能於平台給予您評價。若未點擊「完成服務」，將視為尚未服務。"></i></span></a><br>2020-11-17 午餐</td>
                <td rowspan="2" class="waitpoint"><i class="fa fa-plus" style="margin-right: 10px;"></i>500點</td>
            </tr>
            <tr>
                <td class="tbrecord_tb"><span>收益 - <a href="@Url.Action("salesitem","Fontend")">套餐/課程名稱</a> - <a href="@Url.Action("clientinfo","Fontend")">客戶名稱</a></span></td>
            </tr>
        </table>
        <table class="tbrecord">
            <tr>
                <td><span class="span_left">2020-10-10 14:00</span></td>
                <td rowspan="2" class="statussytle"><span class="waitstatus">完成未被評價</span><br>2020-11-17 午餐</td>
                <td rowspan="2" class="waitpoint"><i class="fa fa-plus" style="margin-right: 10px;"></i>500點</td>
            </tr>
            <tr>
                <td class="tbrecord_tb"><span>收益 - <a href="@Url.Action("salesitem","Fontend")">套餐/課程名稱</a> - <a href="@Url.Action("clientinfo","Fontend")">客戶名稱</a></span></td>
            </tr>
        </table>
        <table class="tbrecord">
            <tr>
                <td><span class="span_left">2020-10-10 14:00</span></td>
                <td rowspan="2" class="statussytle"><span class="bluestatus">完成並獲得評價</span><br>2020-11-17 午餐</td>
                <td rowspan="2" class="addpoint"><i class="fa fa-plus" style="margin-right: 10px;"></i>500點</td>
            </tr>
            <tr>
                <td class="tbrecord_tb"><span>收益 - <a href="@Url.Action("salesitem","Fontend")">套餐/課程名稱</a> - <a href="@Url.Action("clientinfo","Fontend")">客戶名稱</a></span></td>
            </tr>
        </table>


    </div>
</div>
<!-- ##### transaction End ##### -->